#!/bin/bash
#
# tervitusskript
#
echo -n "Tere, " # väljasta ilma reavahetuseta Tere,
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `whoami | cut -c2-`
echo "!" # väljasta ! ja tee reavahetus
#
# skripti lõpp
