#!/bin/bash
#
#ülesanne 2
echo -n "Sisesta aluskandiku pikkus: "
read pikkus
echo -n "Sisesta aluskandiku laius: "
read laius
echo -n "Sisesta küpsise pikkus: "
read kookp
echo -n "Sisesta küpsise laius: "
read kookl
echo -n "Sisesta kihtide arv: "
read kihid
echo -n "Küpsise arv pakis: "
read pakk
#kandiku pindala
pindala=`expr $pikkus \* $laius`
#küpsise pindala
kpind=`expr $kookl \* $kookp`
#mitu küpsist kihis
karv=`expr $pindala / $kpind`
#mitu küpsist kokku
kokku=`expr $karv \* $kihid`
#mitu pakki küpsist
mitupakki=`expr $kokku / $pakk`
#mitu puudu täis pakist
jaak=`expr $kokku % $pakk`
echo "Kokku on vaja $mitupakki pakki ja $jaak küpsist"
#
#
#lõpp
