#!/bin/bash
#
#abi skript bussi ekskursiooni korraldajale
echo -n "Sisestage reisijate arv: "
read inimesed
echo -n "Sisestage bussi istekohtade arv: "
read istekohad
#mitu bussi täidetakse
busside_arv=`expr $inimesed / $istekohad`
#mitu inimest maha jääb
maha_jaab=`expr $inimesed % $istekohad`
echo "Täielikult täidetakse $busside_arv bussi ja maha jääb $maha_jaab inimest"
#
#lõpp
#

