#!/bin/bash
#
#kujundi väljastamine
#
for (( i = 1; i <= 5; i++ )) # loopi pikkus
do
	for (( j = 1; j <= 1; j++)) # loopi laius
	do
		echo -n "$i "
	done
#
	echo "******" #tärnid et kujund moodustada
done
#
#lõpp 

